DROP DATABASE IF EXISTS Project4_Team7;
CREATE DATABASE Project4_Team7;
USE Project4_Team7;

CREATE TABLE Users (
    UserID INT AUTO_INCREMENT,
    Username VARCHAR(50) NOT NULL;
    Pass VARCHAR(255) NOT NULL,
    PRIMARY KEY (UserID)
);

CREATE TABLE Classes (
    ClassID INT AUTO_INCREMENT,
    ClassName VARCHAR(100),
    ClassNumber INT NOT NULL,
    PRIMARY KEY (ClassID)
);

CREATE TABLE Login (
    UserID INT,
    ClassID INT,
    Last_Login DATETIME,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (ClassID) REFERENCES Classes(ClassID) ON DELETE CASCADE,
    CONSTRAINT UQ_Login UNIQUE (UserID, ClassID)
);

CREATE TABLE Student (
    UserID INT,
    ClassID INT,
    Enrolled BOOLEAN,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (ClassID) REFERENCES Classes(ClassID) ON DELETE CASCADE,
    CONSTRAINT UQ_Student UNIQUE (UserID, ClassID)
);